name: package

on:
  workflow_call:
    inputs:
      tag:
        description: 'Annotated tag name'
        type: string
        required: true
      message:
        description: 'Annotated tag message'
        type: string
        required: true

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag -a ${{ github.event.inputs.tag }} -m "${{ github.event.inputs.message }}"
          git push origin ${{ github.event.inputs.tag }}

  package:
    needs:
      - create_tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: refs/tags/${{ github.event.inputs.tag }}

      - name: package jsonld utility
        working-directory: jsonld-utility/
        run: |
          mvn -B package --file pom.xml

      - name: upload jsonld utility
        uses: actions/upload-artifact@v3
        with:
          name: vocab-jsonld-utility
          path: jsonld-utility/target/vocab-jsonld-utility-*.jar

  release_tag:
    needs:
      - package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: refs/tags/${{ github.event.inputs.tag }}

      - name: Get jsonld utility
        uses: actions/download-artifact@v3
        with:
          name: vocab-jsonld-utility
          path: ./

      - name: Create Releases
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.tag }}
          artifacts: '**/*.jar'
          token: ${{ secrets.GITHUB_TOKEN }}
