name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Annotated tag name'
        required: true
      message:
        description: 'Annotated tag message'
        required: true

jobs:
  release:
    uses: ./github/workflows/package.yml
    with:
      tag: ${{ inputs.tag }}
      message: ${{ inputs.message }}
    secrets: inherit
